### ISSUE TITLE
Orphaned Snapshots not cleaned up

### ISSUE THREAD

**Issue by webmin88** [rackerlabs/ebs_snapper#14]
We've noted and confirmed that once an instance is removed, the snapshots are orphaned and no longer cleaned up. This results in snapshots piling up as organizations who are cloud savvy scale in and out on a daily basis. This represents a growing cost for organizations using this tool.

**Comment by alexoughton** [comment]
To clarify, 5,987 represents all snapshots on BCG's accounts which:

1. Are of deleted volumes
2. Are not referenced by an AMI
3. Have a DeleteOn tag in the past

**Comment by martinb3** [comment]
We probably need to clarify in the README that this tool is not a great one for backing up autoscaling instances; in a cloudy world, autoscaling instances wouldn't have any permanent data storage or need backups at all.

We had this in mind: https://12factor.net/processes
> Twelve-factor processes are stateless and share-nothing. Any data that needs to persist must be stored in a stateful backing service, typically a database.

**Comment by martinb3** [comment]
PS -- I'll be working on this in the next day or so, to go ahead and add a flag so we can opt-in customers to throw away snapshots when we can't figure out retention calculations.

**Comment by alexoughton** [comment]
We need to re-open this, as the changes made do not address our concerns. We'll sync-up on this later today.

**Comment by martinb3** [comment]
Okay -- we'll await further detail from you 👍
