### ISSUE TITLE
Improve Errors When Encountering Bad Configuration Data

### ISSUE THREAD

**Issue by bgshacklett** [rackerlabs/ebs_snapper#28]
EBS Snapper Version: 0.6.1

I recently came across an installation which had a syntax error in one of the snapshot configuration items (a missing comma, to be precise). The log output generated when hitting this configuration item was less than helpful:

```
Expecting ',' delimiter: line 1 column 60 (char 59): ValueError
Traceback (most recent call last):
File "/var/task/lambdas.py", line 98, in lambda_snapshot
message_json['region'])
File "/var/task/ebs_snapper/snapshot.py", line 73, in perform_snapshot
configurations = dynamo.list_configurations(context, installed_region)
File "/var/task/ebs_snapper/dynamo.py", line 66, in list_configurations
json_item = json.loads(str_item)
File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib64/python2.7/json/decoder.py", line 380, in raw_decode
obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 1 column 60 (char 59)
```

It would be very helpful to have a descriptive message in the log output which would assist in directing the reader towards the issue; e.g.:
```
A syntax error was encountered in the configuration item \<id\>. The error was: Expecting ',' delimiter: line 1 column 60 (char 59): ValueError':
"ignore": ["\<vol1\>", "\<vol2\>_" "_\<vol3"\>]
----------------------------------^
```

**Comment by martinb3** [comment]
Thanks for reporting this! We're actually now validating all configurations before they are stored, to hopefully avoid this in the future. I'm also about to push up a PR that addresses better error messages for any configurations that snuck in before we were validating them on save.
