### ISSUE TITLE
Sanity check feature doesn't work

### ISSUE THREAD

**Issue by RichieSM** [rackerlabs/ebs_snapper#62]
I'm using version 0.8.1 as per:

`git clone git@github.com:rackerlabs/ebs_snapper.git -b v0.8.1`

```
$ ebs-snapper configure -c -a 123456789
usage: ebs-snapper configure [-h] (-l | -g | -s | -d) [-a [AWS_ACCOUNT_ID]]
                             [object_id] [configuration_json]
ebs-snapper configure: error: one of the arguments -l/--list -g/--get -s/--set -d/--delete is required
```

It looks like it's not aware of the -c option.

**Comment by martinb3** [comment]
@RichieSM It hasn't been in a released version yet. You'll need to use master for now. I'll do a release imminently.
