### ISSUE TITLE
Can't download zip file

### ISSUE THREAD

**Issue by fabiankaeser** [rackerlabs/ebs_snapper#99]
Download link(s) in the readme are not working anymore:
403 Forbidden

Tried: wget -O ebs_snapper.zip s3.amazonaws.com/production-ebs-snapper/v0.10.6/ebs_snapper.zip 
as well as multiple versions listed in http://s3.amazonaws.com/production-ebs-snapper/

all of them throw a 403

**Comment by johnctitus** [comment]
Hey @fabiankaeser 

Apologies, it look like we had something off on our S3 bucket.  Everything should be fixed up now.  If you could give the download another try and let us know if you still run into problems.

**Comment by fabiankaeser** [comment]
Hi @johnctitus 

I can confirm that downloads are working again.

Thank you for the fast reply and the great tool!

Much appreciated

**Comment by johnctitus** [comment]
Glad to hear it, and thank you for the kind words.
